#!/bin/bash
# Human Device Yii 2 deployer v3
# ========================================================
# -h, --help for help

# SETTINGS
# ========================================================

# project host folder name
HOST=""

# default environment name for Yii 2 init
ENV="Development"

# SVN/GIT credentials
REPO_TYPE="GIT"
REPO_URL=''
REPO_USER=''
REPO_PASS=''

# SVN/GIT branch path for development release
DEV_BRANCH='master'

# folders owner and group if needed (use chown syntax)
RIGHTS=""

# project name (just for display)
PROJECT="YII 2"

# production releases folder name
R_FOLDER="releases"

# development current release folder name
DC_FOLDER="dev_current"

# development next release folder name
DN_FOLDER="dev_next"

# composer folder name for vendor storage
C_FOLDER="composer"

# temporary composer folder name for vendor storage
C_TEMP_FOLDER="composer_temp"

# load cfg settings
# ========================================================
if [[ -e "./deployer.cfg" ]]; then
    source "./deployer.cfg"
fi

# script variables
# ========================================================
VERSION=""
VERBOSE=0
USING_TEMPORARY_COMPOSER=0
MODE=0
COMPOSER_DONT_UPDATE=0
DELETE_ENVS=1

# generate line with dots
LINE() {
    local LINE=$(printf '%0.1s' "."{1..60})
    printf "%s%s" "$1" "${LINE:${#1}}"
}

# cleans temporary folder
END_MARKER() {
    if [[ $USING_TEMPORARY_COMPOSER -eq 1 ]]; then
        LINE " > deleting temporary composer folder"
        if rm -rf "./${C_TEMP_FOLDER}"
        then
            echo "deleted"
        fi
    fi
    if [[ $DELETE_ENVS -eq 1 ]]; then
        LINE " > deleting environments folder"
        if rm -rf "./${HOST}/environments"
        then
            echo "deleted"
        fi
    fi
    echo "FINISHED at $(date +"%r")."
}

# creates folder
CREATE_FOLDER() {
    LINE "$1"
    if mkdir "$2"
    then
        chmod 0775 "$2"
        if [[ "$RIGHTS" != "" ]]; then
            chown ${RIGHTS} "$2"
        fi
        echo "created"
        return 1
    fi
    return 0
}

# initialises release folder
INIT_RELEASE_FOLDER() {
    if [[ ! -d "./${R_FOLDER}"  ]]; then
        CREATE_FOLDER " > initialing releases folder" "./${R_FOLDER}"
        if [[ $? -eq 0 ]]; then
            return 0
        fi
    fi
    LINE " > checking release ${1} folder"
    if [[ -d "./${R_FOLDER}/$1" ]]; then
        echo "ALREADY EXISTS! > exit with error"
    else
        echo "ok"
        return 1
    fi
    return 0
}

# initialises development folder
INIT_DEVELOPMENT_FOLDER() {
    if [[ ! -d "./${R_FOLDER}"  ]]; then
        CREATE_FOLDER " > initialing releases folder" "./${R_FOLDER}"
        if [[ $? -eq 0 ]]; then
            return 0
        fi
    fi
    if [[ -d "./${R_FOLDER}/${DN_FOLDER}" ]]; then
        LINE " > deleting old next development release folder"
        if rm -rf "./${R_FOLDER}/${DN_FOLDER}"
        then
            echo "deleted"
        else
            return 0
        fi
    fi
    return 1
}

# checks release folder
CHECK_RELEASE_FOLDER() {
    LINE " > checking release ${1} folder"
    if [[ ! -d "./${R_FOLDER}/$1" ]]; then
        echo "NOT FOUND! > exit with error"
    else
        echo "ok"
        return 1
    fi
    return 0
}

# exporting production release SVN folder
DOWNLOAD_PROD_RELEASE_SVN() {
    LINE " > exporting SVN snapshot"
    local CMD="svn export -q \"${REPO_URL}/tags/${1}\" \"./${R_FOLDER}/${1}\" --no-auth-cache --non-interactive --trust-server-cert --username \"${REPO_USER}\" --password '${REPO_PASS}'"
    if [[ $VERBOSE -eq 1 ]]; then
        CMD="svn export \"${REPO_URL}/tags/${1}\" \"./${R_FOLDER}/${1}\" --no-auth-cache --non-interactive --trust-server-cert --username \"${REPO_USER}\" --password '${REPO_PASS}'"
    fi
    if eval "$CMD"
    then
        return 1
    fi
    return 0
}

# cloning production release GIT folder
DOWNLOAD_PROD_RELEASE_GIT() {
    LINE " > cloning GIT branch"
    local CMD="git clone -q -b \"${1}\" --single-branch '${REPO_USER}:${REPO_PASS}@${REPO_URL}' \"./${R_FOLDER}/${1}\""
    if [[ $VERBOSE -eq 1 ]]; then
        CMD="git clone -v -b \"${1}\" --single-branch '${REPO_USER}:${REPO_PASS}@${REPO_URL}' \"./${R_FOLDER}/${1}\""
    fi
    if eval "$CMD"
    then
        return 1
    fi
    return 0
}

# downloads production release folder
DOWNLOAD_PROD_RELEASE() {
    if [[ "$REPO_TYPE" = "GIT" ]]; then
        DOWNLOAD_PROD_RELEASE_GIT "$1"
        if [[ $? -eq 0 ]]; then
            return 0
        fi
    elif [[ "$REPO_TYPE" = "SVN" ]]; then
        DOWNLOAD_PROD_RELEASE_SVN "$1"
        if [[ $? -eq 0 ]]; then
            return 0
        fi
    else
        echo " > UNSUPPORTED REPO TYPE: only GIT and SVN are allowed! > exit with error"
        return 0
    fi
    echo "done"
    if [[ "$RIGHTS" != "" ]]; then
        chown -R ${RIGHTS} "./${R_FOLDER}/${1}"
    fi
    return 1
}

# exporting development release SVN folder
DOWNLOAD_DEV_RELEASE_SVN() {
    LINE " > exporting development SVN snapshot"
    local CMD="svn export -q \"${REPO_URL}/${DEV_BRANCH}\" \"./${R_FOLDER}/${DN_FOLDER}\" --no-auth-cache --non-interactive --trust-server-cert --username \"${REPO_USER}\" --password '${REPO_PASS}'"
    if [[ $VERBOSE -eq 1 ]]; then
        CMD="svn export \"${REPO_URL}/${DEV_BRANCH}\" \"./${R_FOLDER}/${DN_FOLDER}\" --no-auth-cache --non-interactive --trust-server-cert --username \"${REPO_USER}\" --password '${REPO_PASS}'"
    fi
    if eval "$CMD"
    then
        return 1
    fi
    return 0
}

# cloning development release GIT folder
DOWNLOAD_DEV_RELEASE_GIT() {
    LINE " > cloning development GIT snapshot"
    local CMD="git clone -q -b \"${DEV_BRANCH}\" --single-branch '${REPO_USER}:${REPO_PASS}@${REPO_URL}' \"./${R_FOLDER}/${DN_FOLDER}\""
    if [[ $VERBOSE -eq 1 ]]; then
        CMD="git clone -v -b \"${DEV_BRANCH}\" --single-branch '${REPO_USER}:${REPO_PASS}@${REPO_URL}' \"./${R_FOLDER}/${DN_FOLDER}\""
    fi
    if eval "$CMD"
    then
        return 1
    fi
    return 0
}

# downloads development release folder
DOWNLOAD_DEV_RELEASE() {
    if [[ "$REPO_TYPE" = "GIT" ]]; then
        DOWNLOAD_DEV_RELEASE_GIT
        if [[ $? -eq 0 ]]; then
            return 0
        fi
    elif [[ "$REPO_TYPE" = "SVN" ]]; then
        DOWNLOAD_DEV_RELEASE_SVN
        if [[ $? -eq 0 ]]; then
            return 0
        fi
    else
        echo " > UNSUPPORTED REPO TYPE: only GIT and SVN are allowed! > exit with error"
        return 0
    fi
    echo "done"
    if [[ "$RIGHTS" != "" ]]; then
        chown -R ${RIGHTS} "./${R_FOLDER}/${DN_FOLDER}"
    fi
    return 1
}

# installs composer dependencies
COMPOSER_INSTALL() {
    LINE " > installing composer dependencies"
    if [[ $USING_TEMPORARY_COMPOSER -eq 1 ]]; then
        cd "./${C_TEMP_FOLDER}"
    else
        cd "./${C_FOLDER}"
    fi
    local CMD="composer install -q"
    if [[ $VERBOSE -eq 1 ]]; then
        CMD="composer install"
    fi
    local NODEV=""
    if [[ "$ENV" = "Production" ]]; then
        NODEV="--no-dev --optimize-autoloader"
    fi
    if eval "$CMD $NODEV"
    then
        echo "installed"
        cd ..
        return 1
    fi
    cd ..
    return 0
}

# updates composer dependencies
COMPOSER_UPDATE() {
    if [[ $COMPOSER_DONT_UPDATE -eq 1 ]]; then
        return 1
    fi
    LINE " > updating composer dependencies"
    cd "./${C_FOLDER}"
    local CMD="composer update -q"
    if [[ $VERBOSE -eq 1 ]]; then
        CMD="composer update"
    fi
    local NODEV=""
    if [[ "$ENV" = "Production" ]]; then
        NODEV="--no-dev --optimize-autoloader"
    fi
    if eval "$CMD $NODEV"
    then
        echo "updated"
        cd ..
        return 1
    fi
    cd ..
    return 0
}

# checks vendor folder
CHECK_VENDOR() {
    if [[ ! -d "./${C_FOLDER}" ]]; then
        CREATE_FOLDER " > creating composer folder" "./${C_FOLDER}"
        if [[ $? -eq 0 ]]; then
            return 0
        fi
    fi
    LINE " > checking release ${1} composer.json"
    if [[ ! -e "./${R_FOLDER}/$1/composer.json" ]]; then
        echo "NO COMPOSER.JSON FOUND! > exit with error"
        return 0
    else
        echo "ok"
    fi
    if [[ ! -e "./${C_FOLDER}/composer.json" ]]; then
        LINE " > copying composer.json from release ${1} folder"
        if cp "./${R_FOLDER}/$1/composer.json" "./${C_FOLDER}"
        then
            echo "copied"
            COMPOSER_INSTALL
            if [[ $? -eq 0 ]]; then
                return 0
            fi
            return 1
        fi
    else
        LINE " > comparing deployed and vendor composer.json versions"
        if [[ $(stat -c%s "./${C_FOLDER}/composer.json") -eq $(stat -c%s "./${R_FOLDER}/${1}/composer.json") ]]; then
            echo "matching"
            COMPOSER_UPDATE
            if [[ $? -eq 0 ]]; then
                return 0
            fi
            return 1
        else
            echo "different"
            CREATE_FOLDER " > creating temporary composer folder" "./${C_TEMP_FOLDER}"
            if [[ $? -eq 0 ]]; then
                return 0
            fi
            USING_TEMPORARY_COMPOSER=1
            LINE " > copying composer.json from release ${1} folder"
            if cp "./${R_FOLDER}/${1}/composer.json" "./${C_TEMP_FOLDER}"
            then
                echo "copied"
                COMPOSER_INSTALL
                if [[ $? -eq 0 ]]; then
                    return 0
                fi
                return 1
            fi
        fi
    fi
    return 0
}

# symlinks folders
SYMLINK() {
    LINE " > symlinking vendor folder to release $1"
    local CMD="ln -s \"./../../${C_FOLDER}/vendor\" \"./${R_FOLDER}/${1}/vendor\""
    if [[ $USING_TEMPORARY_COMPOSER -eq 1 ]]; then
        CMD="ln -s \"./../../${C_TEMP_FOLDER}/vendor\" \"./${R_FOLDER}/${1}/vendor\""
    fi
    if eval "$CMD"
    then
        echo "done"
        return 1
    fi
    return 0
}

# starts Yii 2 init
INIT() {
    LINE " > running Yii 2 init for ${ENV}"
    local CMD="php \"./${R_FOLDER}/${1}/init\" --env=${ENV} --overwrite=All >/dev/null"
    if [[ $VERBOSE -eq 1 ]]; then
        CMD="php \"./${R_FOLDER}/${1}/init\" --env=${ENV} --overwrite=All"
    fi
    if eval "$CMD"
    then
        echo "done"
        return 1
    fi
    return 0
}

# switches temporary composer folder
SWITCH_TEMP_COMPOSER() {
    if [[ $USING_TEMPORARY_COMPOSER -eq 1 ]]; then
        if rm "./${R_FOLDER}/${1}/vendor"
        then
            if rm -rf "./${C_FOLDER}"
            then
                if cp -a "./${C_TEMP_FOLDER}" "./${C_FOLDER}"
                then
                    if ln -s "./../../${C_FOLDER}/vendor" "./${R_FOLDER}/${1}/vendor"
                    then
                        return 1
                    fi
                fi
            fi
        fi
    else
        return 1
    fi
    return 0
}

# symlinks release
SYMLINK_RELEASE() {
    SWITCH_TEMP_COMPOSER "$1"
    if [[ $? -eq 1 ]]; then
        if ln -s "./${R_FOLDER}/${1}" "./${HOST}"
        then
            echo "released"
            return 1
        fi
    fi
    return 0
}

# creates backup
BACKUP_CREATE() {
    LINE " > creating host symlink and vendor backup"
    if cp -a "./${HOST}" "./${HOST}_backup"
    then
        if cp -a "./${C_FOLDER}/vendor" "./${C_FOLDER}/vendor_backup"
        then
            echo "done"
            return 1
        fi
    fi
    return 0
}

# deletes backup
BACKUP_DELETE() {
    LINE " > deleting host symlink and vendor backup"
    if rm "./${HOST}_backup"
    then
        if rm -rf "./${C_FOLDER}/vendor_backup"
        then
            echo "deleted"
        fi
    fi
}

# recovers backup
BACKUP_RECOVER() {
    LINE " > recovering host symlink and vendor from backup"
    if [[ -d "./${C_FOLDER}/vendor" ]]; then
        rm -rf "./${C_FOLDER}/vendor"
    fi
    if cp -a "./${C_FOLDER}/vendor_backup" "./${C_FOLDER}/vendor"
    then
        if cp -a "./${HOST}_backup" "./${HOST}"
        then
            echo "recovered"
        fi
    fi
}

# switches production releases
SWITCH() {
    if [[ ! -h "./${HOST}" ]]; then
        LINE " > symlinking ${HOST} to release $1"
        SYMLINK_RELEASE "$1"
        if [[ $? -eq 1 ]]; then
            return 1
        fi
    else
        BACKUP_CREATE
        if [[ $? -eq 1 ]]; then
            LINE " > switching to release $1"
            if rm "./${HOST}"
            then
                SYMLINK_RELEASE "$1"
                if [[ $? -eq 1 ]]; then
                    BACKUP_DELETE
                    return 1
                else
                    BACKUP_RECOVER
                fi
            fi
            BACKUP_DELETE
        fi
    fi
    return 0
}

# moves next development release to current
MOVEDEV() {
    if [[ -d "./${R_FOLDER}/${DC_FOLDER}" ]]; then
        LINE " > removing old current development release"
        if rm -rf "./${R_FOLDER}/${DC_FOLDER}"
        then
            echo "done"
        else
            return 0
        fi
    fi
    LINE " > moving next development release to current"
    if cp -a "./${R_FOLDER}/${DN_FOLDER}" "./${R_FOLDER}/${DC_FOLDER}"
    then
        echo "done"
        rm -rf "./${R_FOLDER}/${DN_FOLDER}"
    else
        return 0
    fi
    return 1
}

# deploys tag
DEPLOY() {
    echo "STARTING deployment of ${PROJECT} version ${VERSION} at $(date +"%r")."
    INIT_RELEASE_FOLDER "$VERSION"
    if [[ $? -eq 1 ]]; then
        DOWNLOAD_PROD_RELEASE "$VERSION"
        if [[ $? -eq 1 ]]; then
            CHECK_VENDOR "$VERSION"
            if [[ $? -eq 1 ]]; then
                SYMLINK "$VERSION"
                if [[ $? -eq 1 ]]; then
                    INIT "$VERSION"
                    if [[ $? -eq 1 ]]; then
                        SWITCH "$VERSION"
                    fi
                fi
            fi
        fi
    fi
    END_MARKER
}

# rollbacks tag
ROLLBACK() {
    echo "STARTING rollback of ${PROJECT} to version ${VERSION} at $(date +"%r")."
    CHECK_RELEASE_FOLDER "$VERSION"
    if [[ $? -eq 1 ]]; then
        CHECK_VENDOR "$VERSION"
        if [[ $? -eq 1 ]]; then
            SYMLINK "$VERSION"
            if [[ $? -eq 1 ]]; then
                SWITCH "$VERSION"
            fi
        fi
    fi
    END_MARKER
}

# deploys development
DEPLOYDEV() {
    echo "STARTING deployment of ${PROJECT} development version at $(date +"%r")."
    INIT_DEVELOPMENT_FOLDER
    if [[ $? -eq 1 ]]; then
        DOWNLOAD_DEV_RELEASE
        if [[ $? -eq 1 ]]; then
            CHECK_VENDOR "$DN_FOLDER"
            if [[ $? -eq 1 ]]; then
                MOVEDEV
                if [[ $? -eq 1 ]]; then
                    SYMLINK "$DC_FOLDER"
                    if [[ $? -eq 1 ]]; then
                        INIT "$DC_FOLDER"
                        if [[ $? -eq 1 ]]; then
                            SWITCH "$DC_FOLDER"
                        fi
                    fi
                fi
            fi
        fi
    fi
    END_MARKER
}

# creates config file
CREATECONFIG() {
    echo "This will create new deployer.cfg file and overwrite existing one."
    read -p "Are you sure? (Y/n) " -n 1 -r
    if [[ $REPLY =~ ^[Nn]$ ]]
    then
        echo ""
        LINE " > creating deployer.cfg file"
    
        echo "# project host folder name" > ./deployer.cfg
        echo "HOST=\"change me\"" >> ./deployer.cfg
        echo "" >> ./deployer.cfg
        echo "# default environment name for Yii 2 init" >> ./deployer.cfg
        echo "ENV=\"change me\"" >> ./deployer.cfg
        echo "" >> ./deployer.cfg
        echo "# SVN/GIT credentials" >> ./deployer.cfg
        echo "REPO_TYPE='GIT'" >> ./deployer.cfg
        echo "REPO_URL='change me'" >> ./deployer.cfg
        echo "REPO_USER='change me'" >> ./deployer.cfg
        echo "REPO_PASS='change me'" >> ./deployer.cfg
        echo "" >> ./deployer.cfg
        echo "# SVN/GIT branch path for development release" >> ./deployer.cfg
        echo "DEV_BRANCH='master'" >> ./deployer.cfg
        echo "" >> ./deployer.cfg
        echo "# folders owner and group if needed (use chown syntax)" >> ./deployer.cfg
        echo "RIGHTS=''" >> ./deployer.cfg
        echo "" >> ./deployer.cfg
        echo "# project name (just for display)" >> ./deployer.cfg
        echo "PROJECT=\"change me\"" >> ./deployer.cfg
    
        echo "done"
    fi
    echo ""
}

# updates deployer
UPDATE() {
    echo " > updating deployer in global mode:"
    composer global update humandevice/deployer
    VENDOR=$(composer global config vendor-dir --absolute)
    composer run-script post-update-cmd -d $VENDOR/humandevice/deployer
    echo ""
}

# starts script
START() {
    if [[ $MODE -eq 6 ]]; then
        CREATECONFIG
    elif [[ $MODE -eq 7 ]]; then
        trap UPDATE SIGHUP SIGINT SIGTERM
    elif [[ $MODE -eq 1 ]]; then
        echo "NAME"
        echo ""
        echo "    deployer v3 - deploy SVN/GIT version of Yii 2 project"
        echo ""
        echo "SYNOPSIS"
        echo ""
        echo "    deployer -d TAG [-v] [-n] [-e ENV]"
        echo "    deployer -r TAG [-v] [-n] [-e ENV]"
        echo "    deployer -dev [-v] [-n] [-e ENV]"
        echo "    deployer -b BRANCH [-v] [-n] [-e ENV]"
        echo "    deployer -h"
        echo "    deployer -c"
        echo "    deployer -u"
        echo ""
        echo "DESCRIPTION"
        echo ""
        echo "    Deploys the target TAG version of Yii 2 project or rollbacks to the target TAG version."
        echo "    Creates the releases and composer folders. Deployed version is stored in the releases"
        echo "    folder under the TAG name. Composer folder stores the vendor folder with composer "
        echo "    dependencies. TAG version is SVN imported or GIT cloned using provided credentials."
        echo "    Deployed or rollbacked version is symlinked to the Apache host target folder."
        echo ""
        echo "    -d TAG, --deploy TAG"
        echo "        deploy TAG version"
        echo ""
        echo "    -r TAG, --rollback TAG"
        echo "        rollback to TAG version"
        echo ""
        echo "    -dev"
        echo "        deploy development version"
        echo ""
        echo "    -b BRANCH, --branch BRANCH"
        echo "        deploy development version from BRANCH branch"
        echo ""
        echo "    -v, --verbose"
        echo "        runs the script in verbose mode where output is visible"
        echo ""
        echo "    -n, --noupdate"
        echo "        skips composer update part (composer install ignores this option)"
        echo ""
        echo "    -e ENV, --env ENV"
        echo "        sets environment name ENV for init"
        echo ""
        echo "    -h, --help"
        echo "        this information (ignores other options)"
        echo ""
        echo "    -c, --config"
        echo "        creates deployer.cfg in current folder (ignores other options)"
        echo ""
        echo "    -u, --update"
        echo "        updates deployer using composer in global mode (ignores other options)"
        echo ""
        echo "AUTHOR"
        echo ""
        echo "    Pawel Brzozowski"
        echo ""
        echo "COPYRIGHT"
        echo ""
        echo "    Copyright (c) 2016-2017 Human Device Sp. z o.o."
        echo ""
    elif [[ $MODE -eq 2 ]]; then
        if [[ "$VERSION" = "" ]]; then
            echo "    Version tag missing."
            echo "    For help run"
            echo "        deployer -h"
        else
            DEPLOY "$VERSION"
        fi
    elif [[ $MODE -eq 3 ]]; then
        if [[ "$VERSION" = "" ]]; then
            echo "    Version tag missing."
            echo "    For help run"
            echo "        deployer -h"
        else
            ROLLBACK "$VERSION"
        fi
    elif [[ $MODE -eq 4 ]]; then
        echo "    You can not run deploy, rollback and development deploy at the same time."
        echo "    For help run"
        echo "        deployer -h"
    elif [[ $MODE -eq 5 ]]; then
        if [[ "$DEV_BRANCH" = "" ]]; then
            echo "    Branch missing."
            echo "    For help run"
            echo "        deployer -h"
        else
            DEPLOYDEV
        fi
    elif [[ $MODE -eq 99 ]]; then
        echo "    Unrecognised option."
        echo "    For help run"
        echo "        deployer -h"
    else
        echo "    Yii 2 project deployer."
        echo "    For help run"
        echo "        deployer -h"
    fi
}

while [[ $# -gt 0 ]]
do
    case $1 in
        -c|--config)
            MODE=6
            break
            ;;
        -u|--update)
            MODE=7
            break
            ;;
        -h|--help)
            MODE=1
            break
            ;;
        -v|--verbose)
            VERBOSE=1
            ;;
        -n|--noupdate)
            COMPOSER_DONT_UPDATE=1
            ;;
        -e|--env)
            ENV="$2"
            shift
            ;;
        -dev)
            if [[ $MODE -eq 2 ]]; then
                MODE=4
            elif [[ $MODE -eq 3 ]]; then
                MODE=4
            else
                MODE=5
            fi
            ;;
        -d|--deploy)
            if [[ $MODE -eq 5 ]]; then
                MODE=4
            elif [[ $MODE -eq 3 ]]; then
                MODE=4
            else
                MODE=2
            fi
            VERSION="$2"
            shift
            ;;
        -r|--rollback)
            if [[ $MODE -eq 5 ]]; then
                MODE=4
            elif [[ $MODE -eq 2 ]]; then
                MODE=4
            else
                MODE=3
            fi
            VERSION="$2"
            shift
            ;;
        -b|--branch)
            if [[ $MODE -eq 2 ]]; then
                MODE=4
            elif [[ $MODE -eq 3 ]]; then
                MODE=4
            else
                MODE=5
            fi
            DEV_BRANCH="$2"
            shift
            ;;
        *)
            MODE=99
            break
            ;;
    esac
    shift
done

START
